FROM node:22-slim AS build

WORKDIR /app
COPY src/frontend/package.json src/frontend/package-lock.json* ./
RUN npm config set registry https://mirrors.cloud.tencent.com/npm/
RUN npm install --unsafe-perm && chmod -R 755 node_modules/.bin/
COPY src/frontend/ .
RUN node node_modules/.bin/vue-tsc -b && node node_modules/.bin/vite build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
